arb-dir: lib/core/localization/arb
output-dir: lib/core/localization/generated
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false
synthetic-package: false
untranslated-messages-file: lib/core/localization/arb/untranslated.json
