// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEVXd1dIafmEDE8a2J_cw2irwjhztdwu0',
    appId: '1:458282755207:web:0ec853077ab0686ad08422',
    messagingSenderId: '458282755207',
    projectId: 'one-debt-99ead',
    authDomain: 'one-debt-99ead.firebaseapp.com',
    storageBucket: 'one-debt-99ead.appspot.com',
    measurementId: 'G-7XTB9703ZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAy0NDMPuL2X5smtZW0NoSxa4tDoWefzg',
    appId: '1:458282755207:android:34aa42ded52dcb83d08422',
    messagingSenderId: '458282755207',
    projectId: 'one-debt-99ead',
    storageBucket: 'one-debt-99ead.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC16L_ljtWchw3RwYSYhVbzOm5xOOTP0MM',
    appId: '1:458282755207:ios:fb63a454dae7bb91d08422',
    messagingSenderId: '458282755207',
    projectId: 'one-debt-99ead',
    storageBucket: 'one-debt-99ead.appspot.com',
    iosBundleId: 'dev.svlit.debt',
  );
}
