import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

TextTheme getTextTheme(ColorScheme colorScheme) {
  final Color color = colorScheme.onSurface;
  return TextTheme(
    displayLarge: TextStyle(
      fontFamily: GoogleFonts.rubik().fontFamily,
      letterSpacing: 0,
      wordSpacing: 0,
      fontWeight: FontWeight.bold,
      height: 1,
      color: color,
      fontSize: 40,
    ),
    displayMedium: TextStyle(
      fontFamily: GoogleFonts.rubik().fontFamily,
      letterSpacing: 0,
      wordSpacing: 0,
      fontWeight: FontWeight.bold,
      height: 1,
      color: color,
      fontSize: 40,
    ),
    displaySmall: TextStyle(
      fontFamily: GoogleFonts.rubik().fontFamily,
      letterSpacing: 0,
      wordSpacing: 0,
      fontWeight: FontWeight.bold,
      height: 1,
      color: color,
      fontSize: 40,
    ),
    headlineLarge: TextStyle(
      fontFamily: GoogleFonts.rubik().fontFamily,
      letterSpacing: 0,
      wordSpacing: 0,
      fontWeight: FontWeight.bold,
      height: 1,
      color: color,
      fontSize: 40,
    ),
    headlineMedium: TextStyle(
      fontFamily: GoogleFonts.rubik().fontFamily,
      letterSpacing: 0,
      wordSpacing: 0,
      fontWeight: FontWeight.normal,
      height: 1,
      color: color,
      fontSize: 34,
    ),
    headlineSmall: TextStyle(
      fontFamily: GoogleFonts.rubik().fontFamily,
      letterSpacing: 0,
      wordSpacing: 0,
      fontWeight: FontWeight.normal,
      height: 1,
      color: color,
      fontSize: 24,
    ),
    titleLarge: TextStyle(
      fontFamily: GoogleFonts.mulish().fontFamily,
      letterSpacing: 0,
      wordSpacing: 0,
      fontWeight: FontWeight.normal,
      height: 1,
      color: color,
      fontSize: 20,
    ),
    titleMedium: TextStyle(
      fontFamily: GoogleFonts.mulish().fontFamily,
      letterSpacing: 0,
      wordSpacing: 0,
      fontWeight: FontWeight.normal,
      height: 1,
      color: color,
      fontSize: 16,
    ),
    titleSmall: TextStyle(
      fontFamily: GoogleFonts.mulish().fontFamily,
      letterSpacing: 0,
      wordSpacing: 0,
      fontWeight: FontWeight.normal,
      height: 1,
      color: color,
      fontSize: 14,
    ),
    bodyLarge: TextStyle(
      fontFamily: GoogleFonts.mulish().fontFamily,
      letterSpacing: 0,
      wordSpacing: 0,
      fontWeight: FontWeight.normal,
      height: 1,
      color: color,
      fontSize: 16,
    ),
    bodyMedium: TextStyle(
      fontFamily: GoogleFonts.mulish().fontFamily,
      letterSpacing: 0,
      wordSpacing: 0,
      fontWeight: FontWeight.normal,
      height: 1,
      color: color,
      fontSize: 14,
    ),
    bodySmall: TextStyle(
      fontFamily: GoogleFonts.mulish().fontFamily,
      letterSpacing: 0,
      wordSpacing: 0,
      fontWeight: FontWeight.normal,
      height: 1,
      color: color,
      fontSize: 12,
    ),
    labelLarge: TextStyle(
      fontFamily: GoogleFonts.mulish().fontFamily,
      letterSpacing: 0,
      wordSpacing: 0,
      fontWeight: FontWeight.normal,
      height: 1,
      color: color,
      fontSize: 14,
    ),
    labelMedium: TextStyle(
      fontFamily: GoogleFonts.mulish().fontFamily,
      letterSpacing: 0,
      wordSpacing: 0,
      fontWeight: FontWeight.normal,
      height: 1,
      color: color,
      fontSize: 11,
    ),
    labelSmall: TextStyle(
      fontFamily: GoogleFonts.mulish().fontFamily,
      letterSpacing: 0,
      wordSpacing: 0,
      fontWeight: FontWeight.normal,
      height: 1,
      color: color,
      fontSize: 10,
    ),
  );
}
